### ISSUE TITLE
Modul Dashboard : Pengujian tombol Info Lebih Lanjut pada fitur jumlah pengunjung hari ini

### ISSUE THREAD

**Issue by intanishere-ipteknet** [tantokaya/pkk#17]
Pengguna belum diarahkan ke halaman daftar jumlah pengunjung hari ini.

**Comment by tantokaya** [comment]
Sudah fix, tadinya mau disesuaikan dengan halamannya, tapi untuk saat ini mungkin lebih baik saya matikan, trims
