### ISSUE TITLE
Modul Media : Pengujian data yang ditampilkan pada daftar galeri foto

### ISSUE THREAD

**Issue by intanishere-ipteknet** [tantokaya/pkk#22]
Pengguna diberikan data yang terdiri dari judul foto dan  judul album. Gambar belum bisa ditampilkan.

**Comment by tantokaya** [comment]
Sudah fix, untuk modul album foto dipending dulu sementara ini, untuk pengembangan selanjutnya saja, jadi sementara saya hilangkan dari side menu, trims
