### ISSUE TITLE
Modul Media : Pengujian fungsi tambah data slide dengan tipe file pdf

### ISSUE THREAD

**Issue by intanishere-ipteknet** [tantokaya/pkk#24]
Pengguna tidak disajikan pesan peringatan. Pengguna diarahkan ke halaman error.

**Comment by tantokaya** [comment]
Okey, sudah fix, untuk pengembangan selanjutnya akan diberikan notifikasi kesalahannya, sementara jika upload selain image maka akan kembali ke halaman daftar slide tidak ke halaman error, trims
