### ISSUE TITLE
komentar

### ISSUE THREAD

**Issue by tantokaya** [tantokaya/pkk#7]
Menu komentar di halaman depan belum berfungsi

**Comment by tantokaya** [comment]
tolong segera diselesaikan, trims :)

**Comment by adit-gudhel** [comment]
ko captchanya ilang ya mas di 83? jadinya puskomkreatif ya bukan pkk direktorinya?

**Comment by tantokaya** [comment]
iya direktorinya puskomkreatif di 83

**Comment by tantokaya** [comment]
Captchanya ada kok di front nya pas lihat berita di kolom komentar bawah

**Comment by adit-gudhel** [comment]
maksudnya blm berfungsi gmn mas? komentar di front yg berhasil disimpan itu di moderasi dulu di adpus (admin), default publishnya N

**Comment by tantokaya** [comment]
Ooo sudah ya ? Sori gw kira belum, oke berarti tinggal bagian gw yang belakang, siip, thx

**Comment by adit-gudhel** [comment]
udah gw buat juga mas backendnya coba cek di server deh

**Comment by tantokaya** [comment]
ok

**Comment by tantokaya** [comment]
Fix
